# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: Install nginx
  apt:
    name: nginx

- name: Create nginx cache directory
  file:
    path: /var/cache/nginx
    state: directory

- name: Install nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Install site config
  template:
    src: "transitous.conf.j2"
    dest: "/etc/nginx/sites-available/transitous.conf"

- name: Disable default site configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable nginx sites
  file:
    src: "/etc/nginx/sites-available/transitous.conf"
    dest: "/etc/nginx/sites-enabled/transitous.conf"
    state: link
